# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Miguel Rivera's Website
tagline:             'It''s gonna to be a walk in the cake'
description: >- # this means to ignore newlines until "baseurl:"
  I know at least a bit about Pytohn, Linux, Quantum Chemistry, Jazz, Board Games,
  Literature, and Cooking.

url:                 http://m-rivera.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Miguel Rivera
  url:               https://twitter.com/michaelriver
  email:             mig.riv.c@gmail.com

# Custom vars
version:             1.0.0
